### ISSUE TITLE
docker-compose.postgis.yml uses port 5432

### ISSUE THREAD

**Issue by MarcoDuiker** [geopython/GeoHealthCheck#181]
It would be very nice if there was an easy way to run the postgis container on another port than 5432.

I would think that most systems where GHC is to be run already have a postgis instance running (probably on port 5432). On my systems where I tried I ran into this.

**Comment by justb4** [comment]
Well, the conflict is due to port mapping from the container to the host, which is not a good idea anyway (security). But you can either leave it out or map 5432 within Postgis Docker container to say 5433 on host:

```
  postgis_ghc:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - ghc_pgdb:/var/lib/postgresql/data
    ports:
      - 5433:5432
    # expose:
    #   - 5432
    environment:
      - POSTGRES_USER=ghc
      - POSTGRES_PASSWORD=ghc
      - POSTGRES_DB=ghc
```
or leave it out entirely:
```
  postgis_ghc:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - ghc_pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ghc
      - POSTGRES_PASSWORD=ghc
      - POSTGRES_DB=ghc
```

There is a "trick" I use to connect from the host, like with `psql` to the `postgis` Docker container:

```
export PGHOST=`sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' postgis`
```
